### ISSUE TITLE
Fix changes from inadvertant merge of 12.1-dev changes into 12.0-maint

### ISSUE THREAD

**Issue by aschester** [FRIBDAQ/NSCLDAQ#54]
Read SING_IMAGE for the container path, simplify DDAS ConfigrationParser and tests.

**Comment by rfoxkendo** [comment]
I think newer singularity and apptainer releases have added environment
variables with the full image path.  SING_IMAGE (our variable) should start
to be a last resort.... And even deprecated.
   Another concern hopefully you are aware of:  there are external people
that do native installs and run natively.  I think we want to continue to
be sure they are supported?
   Hopefully I've not ruined your day

Ron

**Comment by rfoxkendo** [comment]
Ron,

The singularity on our debian 10 daq systems does not give the full path in SINGULARITY_CONTAINER, just the name of the image. Installed version is 2.6.1. Since it reads this, and it does exist, I could not run the daq via ssh pipe. What singularity version supports this?

I dont want to mess things up for others obviously. Don't worry, I've ruined my own day plenty already...

I'm at lunch now so probably won't respond for a min.

Aaron

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by aschester** [comment]
<steelhead:~ >singularity --version
2.6.1-dist
<steelhead:~ >. /usr/opt/buster.sh
Singularity: Invoking an interactive shell within container...

<steelhead:~ >echo $SINGULARITY_CONTAINER
frib-buster.img.v4.2

For example on fishtank. I agree that deprecating SING_IMAGE is a good idea if the container path can be deduced from SINGULARITY_CONTAINER. Far as I can tell this is only singularity 3.6+.

**Comment by rfoxkendo** [comment]
Remember APPTAINER_CONTAINER – if that’s defined is better since at some point the apptainer folks are liable to remove the SINGULARITY_* variables. RF Sent from Mail for Windows From: Aaron ChesterSent: Thursday, September 14, 2023 1:11 PMTo: FRIBDAQ/NSCLDAQCc: Ron Fox; CommentSubject: Re: [FRIBDAQ/NSCLDAQ] Fix changes from inadvertant merge of 12.1-dev changes into 12.0-maint (Issue #54) <steelhead:~ >singularity --version2.6.1-dist<steelhead:~ >. /usr/opt/buster.shSingularity: Invoking an interactive shell within container...<steelhead:~ >echo $SINGULARITY_CONTAINERfrib-buster.img.v4.2For example on fishtank. I agree that deprecating SING_IMAGE is a good idea if the container path can be deduced from SINGULARITY_CONTAINER. Far as I can tell this is only singularity 3.6+.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by aschester** [comment]
Yeah, works for apptainer. What i did was to put the SING_IMAGE check before the APPTAINER_CONTAINER one so it will use SING_IMAGE if it exists then check the XXX_CONTAINERs. I should have been more clear about this in my original comment. I did not remove any of the functionality to run natively if those variables are not defined, or remove anything that checked them if they exist. Just reordered.

So its kind of an unfortunate situation, using the XXX_CONTAINER envvars is a lot nicer. But short of requiring singularity 3.6+ to install NSCLDAQ (probably not great since this is a big update on our end too), SING_IMAGE still needs to be defined for at least some singularity users. Perhaps better, one could get the path from, in order:

APPTAINER_CONTAINER
SING_IMAGE if defined otherwise SINGULARITY_CONTAINER
or else its running natively.

but this is still a bit messy since apptainer will potentially bypass whatever the user defines as SING_IMAGE if they arent careful how they launch the container.

**Comment by aschester** [comment]
closed by #62
